### ISSUE TITLE
no .exe file

### ISSUE THREAD

**Issue by ToneZone773** [raphaelradna/SpaceControl#5]
the link provided dose not contain an ".exe" as the manual suggest to properly install the plugin.

**Comment by raphaelradna** [comment]
You need to download the current Windows version, i.e., [Space.Control.1.0.1.WIN.zip](https://github.com/raphaelradna/SpaceControl/releases/download/v1.0.1/Space.Control.1.0.1.WIN.zip).
That contains Space Control.exe, which is an application—not a plug-in installer.
